logLevel = "INFO"

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"

[file]
  [backends]
    [backends.backend1]
      [backends.backend1.loadbalancer]
        method = "wrr"
        sticky = true
      [backends.backend1.servers.server1]
        url = "http://172.17.0.1:4082"

  [frontends]
    [frontends.frontend1]
      backend = "backend1"
      entrypoints = ["http"]

