version: '2'

services:
  front-end:
    image: kingzevin/sock_front-end:0.3.12.1
    container_name: sock_front-end
    ports:
      - '4082:8079'
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: false
  edge-router:
    image: kingzevin/sock_edge-router:0.1.1
    container_name: sock_edge-router
    ports:
      - '4080:80'
      - '4081:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: false
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
  catalogue:
    image: kingzevin/sock_catalogue:0.3.5.1
    container_name: sock_catalogue
    ports:
      - '4083:80'
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    depends_on: 
      - catalogue-db
    read_only: false
  catalogue-db:
    image: kingzevin/catalogue-db:0.3.5.1
    container_name: sock_catalogue-db
    ports:
      - '4306:3306'
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: kingzevin/sock_carts:0.4.8.x
    container_name: sock_carts
    ports:
      - '4084:80'
    hostname: carts
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    depends_on: 
      - carts-db
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  carts-db:
    image: mongo:3.4
    container_name: sock_carts-db
    ports:
      - '4017:27017'
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid
  orders:
    image: kingzevin/sock_orders:0.4.7.1
    container_name: sock_orders
    ports:
      - '4085:80'
    hostname: orders
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    depends_on: 
      - orders-db
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  orders-db:
    image: mongo:3.4
    container_name: sock_orders-db
    ports:
      - '4018:27017'
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid
  shipping:
    image: kingzevin/sock_shipping:0.4.8.1
    container_name: sock_shipping
    ports:
      - '4086:80'
    hostname: shippinoqoog
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  queue-master:
    image: kingzevin/sock_queue-master:0.3.1.1
    container_name: sock_queue-master
    ports:
      - '4087:80'
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    depends_on: 
      - rabbitmq
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8
    container_name: sock_rabbitmq
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: false
  payment:
    image: kingzevin/sock_payment:0.4.3.1
    container_name: sock_payment
    ports:
      - '4088:80'
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
  user:
    image: kingzevin/sock_user:0.4.7.1
    container_name: sock_user
    ports:
      - '4089:80'
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    depends_on: 
      - user-db
    environment:
      - MONGO_HOST=172.17.0.1:4019
  user-db:
    image: weaveworksdemos/user-db:0.4.0
    container_name: sock_user-db
    ports:
      - '4019:27017'
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid
  # user-sim:
  #   image: weaveworksdemos/load-test:0.1.1
  #   container_name: sock_user-sim
  #   cap_drop:
  #     - all
  #   read_only: false
  #   hostname: user-simulator
  #   command: "-d 60 -r 200 -c 2 -h edge-router"
